services:
  - name: ecommerce
    envVars:
      - key: DATABASE_URL
        sync: false
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate  # Add this line
    startCommand: gunicorn ecommerce.wsgi
