services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn ecommerce.wsgi
