# Generated by Django 5.1.5 on 2025-01-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=12)),
                ('project', models.CharField(max_length=255)),
                ('query_description', models.TextField()),
            ],
        ),
    ]
