# Generated by Django 5.1.5 on 2025-01-31 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
