# Generated by Django 5.1.5 on 2025-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contactus_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='query_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
