# Generated by Django 5.1.5 on 2025-02-03 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contactus_datetime_alter_contactus_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
